sudo: required

os: linux

services:
  - docker
    
    
before_install:
  - sudo apt-get -qq update
  - apt-get install -y cmake build-essential pkg-config libssl-dev
  - apt-get install -y libboost-all-dev

before_script: cd project

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
