sudo: required

language: cpp

os: linux

services:
  - docker
    
install:
  # note: use option '-t' for 'docker exec' to enable colored output
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo docker run -it -c "
        apt-get -qq update;
        apt-get install -y cmake build-essential pkg-config libssl-dev;
        apt-get install -y libboost-all-dev
      ";
    fi
    
script:
  - sudo docker run -it -v "$PWD:/repository" -c "
      cd /repository && mkdir build && cd build &&
      cmake .. && make -j4
      "
