os: linux

sudo: enable
    
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake build-essential pkg-config libssl-dev
  - sudo apt-get install -y libboost-all-dev
  - sudo apt-get install libgmp3-dev
  - wget https://crypto.stanford.edu/pbc/files/pbc-0.5.14.tar.gz
  - cd pbc-0.5.14
  - ./configure
  - make
  - sudo make install all
  

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
