sudo: required

language: cpp

os: linux

services:
  - docker
  
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker pull ubuntu:16.04;
      docker run -d -v $(pwd):/zilliqa -v $HOME/.ccache:/root/.ccache -w /zilliqa --name ci ubuntu:16.04 tail -f /dev/null;
    fi
    
install:
  # note: use option '-t' for 'docker exec' to enable colored output
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker exec -t ci /bin/sh -c "
        apt-get -qq update;
        apt-get install -y cmake build-essential pkg-config libssl-dev;
        apt-get install -y libboost-all-dev
      ";
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker exec -t ci /bin/sh -c "
      mkdir build && cmake .. && make -j4
      ";
    fi
