sudo: required

services:
  - docker

script:
  - sudo docker run -it -v "$PWD:/repository" eidheim/testing sh -c "
      cd /repository && mkdir build && cd build && 
      cmake && make -j4
      "
