os: linux

sudo: enable
    
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake build-essential pkg-config libssl-dev
  - sudo apt-get install -y libboost-all-dev

before_script: cd project

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
